import { getInput } from '../../utils/getInput'
import { part1, part2 } from './index'

const data = getInput(__dirname)

const exampleData = `............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............`

test('2024 - Day 8: part 1', () => {
  expect(part1(exampleData)).toBe(14);
  expect(part1(data)).toBe(400);
})

test('2024 - Day 8: part 2', () => {
  expect(part2(exampleData)).toBe(34);
  expect(part2(data)).toBe(1280);
})
